services:
  # ローカル開発環境
  app:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../frontend/.env
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
      - ../../frontend/next.config.mjs:/app/next.config.mjs
      - ../../frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ../../frontend/tsconfig.json:/app/tsconfig.json
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ../../frontend/components.json:/app/components.json
      - ../../../tamanomi-schemas:/app/tamanomi-schemas
    environment:
      - NODE_ENV=development
    command: pnpm dev 