services:
  # ローカル開発環境
  app:
    build:
      context: ../../../
      dockerfile: tamanomi-web/infrastructure/docker/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    env_file:
      - ../../../tamanomi-schemas/.env
      - ../../frontend/.env
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
      - ../../frontend/next.config.mjs:/app/next.config.mjs
      - ../../frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ../../frontend/tsconfig.json:/app/tsconfig.json
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ../../frontend/components.json:/app/components.json
    environment:
      - NODE_ENV=development
    command: pnpm dev 